telegram:
  api-url: ${TELEGRAMURL}
  bot:
    name: ${TELEGRAMNAME}
    token: ${TELEGRAMTOKEN}
spring:
  data:
    mongodb:
      uri: ${DBURL}
      username: ${DBUSER}
      database: ${DBNAME}
  jpa:
    generate-ddl: true