telegram:
  api-url: https://api.telegram.org/
  bot:
    name: ${TELEGRAMNAME:bot}
    token: ${TELEGRAMTOKEN:token}
spring:
  data:
    mongodb:
      uri: mongodb://${DBURL:mongodb}:27017
      username: ${DBUSER:admin}
      database: ${DBNAME:bot}
  jpa:
    generate-ddl: true